"""add cascades

Revision ID: 2e8cfd7ee687
Revises: 497696bbdfbf
Create Date: 2025-11-21 15:56:41.068460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8cfd7ee687'
down_revision = '497696bbdfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('registrations_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('registrations_talk_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'talks', ['talk_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('talks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('talks_speaker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['speaker_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('talks_speaker_id_fkey'), 'user', ['speaker_id'], ['id'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('registrations_talk_id_fkey'), 'talks', ['talk_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('registrations_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
