"""init

Revision ID: 497696bbdfbf
Revises: 9ffcf9987a60
Create Date: 2025-11-21 15:27:24.305919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497696bbdfbf'
down_revision = '9ffcf9987a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###
